spring:
  application:
    name: transfer
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        prefixes: [ config ]
        format: YAML
        defaultContext: application
      scheme: http
      host: yandex-sprint-9-consul
      port: 8500


clients:
  blocker-service:
    url: "http://yandex-sprint-9-blocker:8080"
  account-service:
    url: "http://yandex-sprint-9-account:8080"
  notification-service:
    url: "http://yandex-sprint-9-notification:8080"
  exchange-service:
    url: "http://yandex-sprint-9-exchange:8080"

application:
  scheduling:
    notification-delay: 3000