spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        prefixes: [config]
        format: YAML
        defaultContext: application
      scheme: http
      host: yandex-sprint-9-consul
      port: 8500
    gateway:
      server:
        webflux:
          routes:
            - id: yandex-sprint-9-front-ui-id
              uri: http://yandex-sprint-9-front-ui:8080
              predicates:
                - Path=/, /main
            - id: yandex-sprint-9-exchange-api-rates
              uri: http://yandex-sprint-9-exchange:8080
              predicates:
                - Path=/api/rates

server:
  port: 9090