spring:
  application:
    name: cash
  config:
    import: "optional:consul:"
  r2dbc:
    url: r2dbc:postgresql://yandex-sprint-9-cash-postgres:${YANDEX_SPRINT_9_CASH_POSTGRES_DB_PORT}/${YANDEX_SPRINT_9_CASH_POSTGRES_DB_NAME}
    username: ${YANDEX_SPRINT_9_CASH_POSTGRES_DB_USER_NAME}
    password: ${YANDEX_SPRINT_9_CASH_POSTGRES_DB_USER_PASSWORD}
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://yandex-sprint-9-cash-postgres:${YANDEX_SPRINT_9_CASH_POSTGRES_DB_PORT}/${YANDEX_SPRINT_9_CASH_POSTGRES_DB_NAME}
    user: ${YANDEX_SPRINT_9_CASH_POSTGRES_DB_USER_NAME}
    password: ${YANDEX_SPRINT_9_CASH_POSTGRES_DB_USER_PASSWORD}
    contexts: default
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        prefixes: [ config ]
        format: YAML
        defaultContext: application
      scheme: http
      host: yandex-sprint-9-consul
      port: 8500


clients:
  blocker-service:
    url: "http://yandex-sprint-9-blocker:8080"
  account-service:
    url: "http://yandex-sprint-9-account:8080"
  notification-service:
    url: "http://yandex-sprint-9-notification:8080"


application:
  scheduling:
    enable: true
    notification-delay: 3000
  r2dbc:
    auditing:
      enable: true