spring:
  application:
    name: front-ui
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        prefixes: [ config ]
        format: YAML
        defaultContext: application
      scheme: http
      host: yandex-sprint-9-consul
      port: 8500
  security:
    oauth2:
      client:
        registration:
          bank-services-cc:
            provider: keycloak
            client-id: ${YANDEX_SPRINT_9_KEYCLOAK_INTERNAL_CALL_CLIENT_ID}
            client-secret: ${YANDEX_SPRINT_9_KEYCLOAK_INTERNAL_CALL_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://yandex-sprint-9-keycloak:8080/realms/${YANDEX_SPRINT_9_KEYCLOAK_REALM}/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: http://yandex-sprint-9-keycloak:8080/realms/${YANDEX_SPRINT_9_KEYCLOAK_REALM}/protocol/openid-connect/certs


clients:
  account-service:
    url: "http://yandex-sprint-9-account:8080"


logging:
  level:
    org.springframework.web.reactive.result.method.annotation: DEBUG