application:
  r2dbc:
    auditing:
      enabled: false
spring:
  cloud:
    config.import-check.enabled: false
    consul:
      enabled: false
      config:
        enabled: false
  liquibase.enabled: false
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
    - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
    - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcRepositoriesAutoConfiguration
