application:
  r2dbc:
    auditing:
      enabled: false
spring:
  cloud:
    config.import-check.enabled: false
    consul:
      enabled: false
      config:
        enabled: false
  liquibase.enabled: false
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
    - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
    - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcRepositoriesAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          bank-services-cc:
            provider: keycloak
            client-id: test
            client-secret: test
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:9999/token
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json
