spring:
  application:
    name: exchange-generator
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        prefixes: [config]
        format: YAML
        defaultContext: application
      scheme: http
      host: yandex-sprint-9-consul
      port: 8500

clients:
  exchange-service:
    url: "http://yandex-sprint-9-exchange:8080"

application:
  scheduling:
    enable: true
