spring:
  application:
    name: exchange
  r2dbc:
    url: r2dbc:postgresql://yandex-sprint-9-exchange-postgres:5432/db_exchange
    username: user
    password: pass
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://yandex-sprint-9-exchange-postgres:5432/db_exchange
    user: user
    password: pass
    contexts: default
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate